import { useAuth } from '@/components/authcontextprovider';
import { runner } from '@/components/error';
import { success } from '@/components/success';
import { Anchor, Box, Button, Center, Checkbox, PasswordInput, Stack, TextInput, Title } from '@mantine/core'
import { useForm } from '@mantine/form'
import Head from 'next/head'
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function SignIn() {
    const { signIn } = useAuth();
    const router = useRouter();

    interface signIntypes {
        email: string,
        password: string,
    }

    // function runner(e: any) { 
    //     showNotification({
    //         title: 'Error Code',
    //         message: `${e}`,
    //         color: 'red',
    //     })
    // }

    const form = useForm({
        initialValues: {
            email: '',
            password: '',
        },
        validate: {
            email: (value) => (/^\S+@\S+$/.test(value) ? null : 'Invalid email'),
            password: (value) => (value.length > 6 ? null : 'Password should be longer than 6 words'),
        }
    });

    async function submit(e: signIntypes) {
        try {
            await signIn(e.email, e.password);
            router.push("/dashboard");
            success(false);
            console.log(e);
        } catch (error:any) {
            console.log(error);
            runner(error);
        }
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Center component='main' sx={(theme) => ({
                height: '100vh'
            })}>
                <Box mx="auto" p={`md`} sx={(theme) => ({
                    borderRadius: theme.radius.sm,
                    backgroundColor: theme.colors.gray, 
                    width: `300px`,
                })}>
                    <Center>
                        <Title size={`h4`} mb={`sm`}>Sign In</Title>
                    </Center>
                    <form onSubmit={form.onSubmit((values) => submit(values))}>
                        <Stack spacing={`sm`}>
                            <TextInput
                                withAsterisk
                                label="Email"
                                placeholder="Your Email"
                                {...form.getInputProps('email')}
                            />
                            <PasswordInput
                                placeholder="Password"
                                label="Password"
                                withAsterisk
                                {...form.getInputProps('password')}
                            />

                            <Button type="submit">Sign In</Button>
                            <Center>
                                <Link href={`/signup`}>
                                    <Anchor size={`xs`}>Don&apos;t have a account? Sign Up</Anchor>
                                </Link>
                            </Center>
                        </Stack>
                    </form>
                </Box>
            </Center>
        </>
    )
}
